import {
  readFile,
  writeFile,
  mkdir,
  readdir,
  copyFile,
  rm,
} from "node:fs/promises";
import { resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ROOT,
  loadContent,
  validateContent,
  audioManifest,
  hash,
} from "./lib.mjs";
export async function build(root = ROOT) {
  const c = validateContent(await loadContent(root));
  const out = resolve(root, "public");
  const manifest = audioManifest(c);
  if (manifest.length && !c.config.approved)
    throw Error(
      "Choose and approve the voice after listening to samples before publishing content.",
    );
  await mkdir(resolve(out, "audio"), { recursive: true });
  const names = new Set(manifest.map((x) => x.file.split("/").pop()));
  for (const f of await readdir(resolve(out, "audio")))
    if (!names.has(f)) await rm(resolve(out, "audio", f));
  for (const item of manifest) {
    const name = item.file.split("/").pop();
    const src = resolve(root, "audio-source/clips", name);
    const bytes = await readFile(src).catch(() => {
      throw Error(
        `Missing audio for: ${item.text}. Run audio generation before publishing.`,
      );
    });
    if (bytes.length < 100) throw Error(`Audio too small: ${name}`);
    await copyFile(src, resolve(out, item.file));
  }
  const catalog = {
    course: c.course,
    learned: c.learned,
    lessons: c.lessons.map((l) =>
      l.status === "ready" ? l : { ...l, words: [], rules: [], questions: [] },
    ),
    audio: manifest,
  };
  const shell = [
    "index.html",
    "style.css",
    "app.js",
    "core.js",
    "conjugator.js",
    "manifest.webmanifest",
    "icon.svg",
    "icon-192.png",
    "icon-512.png",
  ];
  const template = await readFile(
    resolve(root, "tools/sw-template.js"),
    "utf8",
  );
  const version = hash(
    Buffer.concat([
      Buffer.from(JSON.stringify(catalog) + template),
      ...(await Promise.all(
        [...shell, ...manifest.map((x) => x.file)].map((f) =>
          readFile(resolve(out, f)),
        ),
      )),
    ]),
  ).slice(0, 12);
  catalog.version = version;
  await writeFile(
    resolve(out, "catalog.js"),
    `// Generated by tools/build.mjs. Edit content/, not this file.\nexport const catalog = ${JSON.stringify(catalog, null, 2)};\n`,
  );
  const assets = await Promise.all(
    [...shell, "catalog.js", ...manifest.map((x) => x.file)].map(
      async (path) => ({
        path,
        sha256: hash(await readFile(resolve(out, path))),
      }),
    ),
  );
  await writeFile(
    resolve(out, "sw.js"),
    `const VERSION=${JSON.stringify(version)};\nconst ASSETS=${JSON.stringify(assets)};\n${template}`,
  );
  await writeFile(resolve(out, ".nojekyll"), "");
  const allowed = new Set([...shell, "catalog.js", "sw.js", ".nojekyll"]);
  for (const f of await readdir(out, { withFileTypes: true })) {
    if (f.isDirectory()) {
      if (f.name !== "audio")
        throw Error(`Unexpected publish directory: ${f.name}`);
    } else if (!allowed.has(f.name))
      throw Error(`Unexpected publish file: ${f.name}`);
  }
  console.log(
    `Built ${version}: ${c.learned.length} learned, ${c.lessons.filter((l) => l.status === "ready").length} ready, ${manifest.length} clips. Public folder contains no source documents or credentials.`,
  );
  return { version, manifest, catalog, assets };
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  await build();
